Feature/install in different workspace
vtex-apps/cms-builder-sf pull request #37
Opened 2020-10-26 17:54 UTC by CarlaCosenza

Adding support to install the store-state in another workspace from master.

2020-10-27 14:45 UTC, mateuspontes requested changes

2020-10-27 14:45 UTC, mateuspontes commented on node/middlewares/listFiles.ts
>  // import { getRouteJSON } from './routes'
can you remove this comment?

```suggestion

```

2020-10-27 14:45 UTC, mateuspontes commented on node/middlewares/checkPublishedApp.ts
> +      console.log('error:', err)
I think is safe to use console `info` and `error`, can you confirm?
```suggestion
      console.error('error:', err)
```

2020-10-27 14:45 UTC, mateuspontes commented on node/middlewares/checkPublishedApp.ts
> +      // )
```suggestion
```

2020-10-27 14:45 UTC, mateuspontes commented on node/middlewares/checkPublishedApp.ts
> +// import Billing, { InstallResponse } from '../clients/billing'
```suggestion
```

2020-10-27 14:45 UTC, mateuspontes commented on node/middlewares/checkPublishedApp.ts
> +  }
Can workspace be null here? Why do we need to check for `=== undefined`?

```suggestion
  if (!targetWorkspace) {
    targetWorkspace = ctx.vtex.workspace
  }
```

2020-10-27 14:45 UTC, mateuspontes commented on node/middlewares/checkPublishedApp.ts
> +      timeout: 10000,
Maybe this is not a good value for the timeout, because we defined 10000 as the default timeout for the entire app.
I think we must use 9000 or less.

2020-10-27 17:36 UTC, CarlaCosenza commented on node/middlewares/checkPublishedApp.ts
> +  }
I made it so that if there is no workspace specified, the app will be installed in the current workspace. That way we will not break with the old CMS inputs.

2020-10-28 19:22 UTC, mateuspontes commented on node/middlewares/checkPublishedApp.ts
> +  let { targetWorkspace } = body
@CarlaCosenza Can you confirm if this payload is correct?

```json
{
  "buildId": "storecomponents.store-state@0.55.0",
  "targetWorkspace: "preview1"
}
```

2020-11-03 21:24 UTC, CarlaCosenza commented on node/middlewares/checkPublishedApp.ts
> +  let { targetWorkspace } = body
Yes, this is what I have been using

2020-11-04 17:57 UTC, felippenardi requested changes

2020-11-04 21:52 UTC, CarlaCosenza commented on node/middlewares/checkPublishedApp.ts
> +  let installResponse: AppInstallResponse = { message: '' }
No, its just an initialization of the install response so we can use it later, since we do the try catch.

2020-11-04 22:04 UTC, CarlaCosenza commented on node/middlewares/checkPublishedApp.ts
> +  let installResponse: AppInstallResponse = { message: '' }
Its because this will be the response of the install after the try catch. Do you still think we should rename the variable?

2020-11-05 14:20 UTC, mateuspontes commented on node/middlewares/checkPublishedApp.ts
> +  let installResponse: AppInstallResponse = { message: '' }
I think it's ok here.

2020-11-05 14:21 UTC, mateuspontes approved these changes

2020-11-05 20:38 UTC, mateuspontes requested changes
Before merge, we need to fix targetWorkspace on publish and unpublish

2020-11-09 17:01 UTC, mateuspontes approved these changes

2021-02-08 15:15 UTC, felippenardi commented
I'm closing this because it is inactive for too long

2021-02-08 15:15 UTC, closed without merging